### ISSUE TITLE
add donation addresses and clean up HTML

### ISSUE THREAD

**Issue by pmaji** [pmaji/crypto-asset-comparison-tool#3]

**Comment by antoniosehk** [comment]
You should put your BTC/ETH/LTC address in QR code so that people can easily transfer crypto to you.

**Comment by pmaji** [comment]
Hey @antoniosehk that's an excellent idea! I hadn't though of that as that is seldom the method I use for transfers. I'll fix that shortly and update you when I have done so :)

**Comment by antoniosehk** [comment]
Donated ETH.
Support your good work !

**Comment by antoniosehk** [comment]
https://www.ethereumqrcode.com/

**Comment by pmaji** [comment]
Thanks again @antoniosehk! Every little bit helps :) I just pushed an update to the README that now includes the QR codes. I haven't thought of way yet to easily integrate donation options into the web app itself, so if you have any ideas for that let me know, but I hope my new addition to the README is what you were looking for :)

**Comment by antoniosehk** [comment]
Wonderful !
Have a nice weekend =]

**Comment by pmaji** [comment]
You too @antoniosehk !
